### ISSUE TITLE
405 method not allowed

### ISSUE THREAD

**Issue by royalamisingh** [adobe/commerce-cif-graphql-integration-reference#19]
### Expected Behaviour
After running npm run deploy  command project should deploy successfully
### Actual Behaviour
After running npm run deploy  command i am getting below error
  Serverless Error ---------------------------------------

  Failed to deploy package (graphql-reference) due to error: PUT https://adobeioruntime.net/%0D/api/v1/namespaces/51906-cifintegration/packages/graphql-reference?overwrite=true Returned HTTP 405 (Method Not Allowed) --> "Response Missing Error Message."
#### Steps to Reproduce
run npm run deploy
[2020-08-10T07_23_09_198Z-debug.log](https://github.com/adobe/commerce-cif-graphql-integration-reference/files/5049537/2020-08-10T07_23_09_198Z-debug.log)
[2020-08-10T07_28_24_911Z-debug.log](https://github.com/adobe/commerce-cif-graphql-integration-reference/files/5049538/2020-08-10T07_28_24_911Z-debug.log)

#### Logs taken while reproducing problem

**Comment by cjelger** [comment]
This is likely a problem in your `.wskprops` where you don't have the right authentication key for your namespace, or in the `APIHOST` parameter: the PUT URL looks strange with that `%0D`(carriage return) after the hostname.

**Comment by royalamisingh** [comment]
Belo is my wsk file properties
AUTH=cc374e95-126e-4d07-9093-815ef50a4c01:4yrnfWRM4Da2bEkWuh60WP3DvMDqOkQ0E3xxQ8i5tNdOc872Df3Mtpb7r73HiMOI
APIHOST=adobeioruntime.net
NAMESPACE=51906-cifintegration

i am able to deploy other actions with same credentials

**Comment by cjelger** [comment]
Do **NOT** share your credentials here !!! This is a public repository and website !!! DELETE your comment !

I just tested and deployed the actions into your workspace, everything works fine. It might be an issue because you use Windows, or maybe something else, you'll have to search.

**Comment by royalamisingh** [comment]
Hi cjelger,Thanks for modifying the comment .

Yes I am using windows,Can you help me to fix it?

**Comment by cjelger** [comment]
I'm sorry I don't have a Windows machine, I cannot help. Again, check why you have that `%0D` part in the URL, this is a URL-encoded "carriage return (CR)" character which is probably an issue related to Windows. It might actually come from the `.wskprops` file at the end of the `APIHOST` line, there might some invisible carriage return character at the end of that line. Or it's maybe a bug in the `serverless` tool.

**Comment by prashantonkar87** [comment]
I faced this same issue. Its due to Carriage return character in `.wskprops` file as mentioned by @cjelger . I removed the CR using notepad++ and it started working fine.

**Comment by royalamisingh** [comment]
@cjelger 
when i am testing the URL "https://adobeioruntime.net/api/v1/web/51906-cifintegration/graphql-reference/dispatcher"  and "https://adobeioruntime.net/api/v1/web/51906-cifintegration/graphql-reference/cif-schema" i am getting below response.Any headers required?

{
  "errors": [
    {
      "locations": [
        {
          "column": 1,
          "line": 1
        }
      ],
      "message": "Syntax Error: Unexpected <EOF>"
    }
  ]
}

**Comment by cjelger** [comment]
Closing, as this is not an issue related to our code.
