### ISSUE TITLE
Get data out mock data from Magento GraphQL response.

### ISSUE THREAD

**Issue by nikhilkumar24dev** [adobe/commerce-cif-graphql-integration-reference#25]
Was trying out the reference project and setup on Adobe IO Runtime.

I have following Raw json response from Magento GraphQl, similarly I want it from Adobe IO endpoint.

How we use it in place of already existing RAW  JSON ?
{
    "data": {
        "products": {
            "items": [
                {
                    "__typename": "ConfigurableProduct",
                    "id": 278,
                    "color": null,
                    "sku": "SKUID01",
                    "name": "Mountain Kit",
                    "description": {
                        "html": "<p>Description</p>"
                    }
                   ]
        }
    }
}

**Comment by cjelger** [comment]
Hello. Well I'm not quite sure what you want to do: if you already have Magento, then you don't need to do any 3rd-party integration unless you want to customise responses or just want to see how it works.

The mock responses are currently "hard-coded" at https://github.com/adobe/commerce-cif-graphql-integration-reference/blob/master/src/common/ProductsLoader.js#L62-L135 for different search options. In a real integration, this entire method would be replaced by some (REST or GraphQL) calls to the e-commerce platform.

I'm still not so sure what exactly you want to do with your Magento response. Do you want to return this response in the Adobe I/O integration?

**Comment by nikhilkumar24dev** [comment]
Thanks @cjelger, Got it!
Just wanted to customize the response coming from Magento in Reference project. I am able to do it now using Catalog.js.
Awesome customization!

**Comment by cjelger** [comment]
ok good. Please close this issue if your problem is solved.
