### ISSUE TITLE
Console error while using Product List in Archetype 24 Project on AEMaaCs SDK.

### ISSUE THREAD

**Issue by nikhilkumar24dev** [adobe/commerce-cif-graphql-integration-reference#28]
@cjelger 

Getting below error while using Product List commerce OOTB component.
![image](https://user-images.githubusercontent.com/71063587/94032168-4d051580-fddd-11ea-997d-51b430b6d143.png)

QUERY should basically resolve on below mentioned resolver only, right ? 
![image](https://user-images.githubusercontent.com/71063587/94046862-dbce5e00-fdee-11ea-8368-5312a92a332a.png)

**Comment by nikhilkumar24dev** [comment]
@cjelger  - I have updated the schema to 2.4.0 that got updated 3-4 days back. Still can see errors and compatibility issue.

**Comment by nikhilkumar24dev** [comment]
@herzog31  @mhaack @cjelger  - I am using the reference 3rd Party Adobe IO endpoint(Schema v2.4.0) but when I pass it through proxy and see the output it shows incompatibility issue.
![image](https://user-images.githubusercontent.com/71063587/94063290-818cc780-fe05-11ea-8a53-2effbe981137.png)


Also the products doesn't get picked up based on the selector. But as I have modified the response in Node Loader I can see two different responses from two different category Id but products doesnt get updated using Selector.
![image](https://user-images.githubusercontent.com/71063587/94063372-9ec19600-fe05-11ea-94e9-3796976ccd2f.png)

**Comment by cjelger** [comment]
The CIF Add-On for AEM as a cloud service is not yet compatible with 2.4.0, there will be a new release by the end of the month or beginning of October. In the mean time, you should continue to use the integration with the `2.3.5` schema. You can checkout the `cif-1.2.0` tag which still has the `2.3.5` schema.

**Comment by cjelger** [comment]
Actually I checked again and yes you're right, the `categories` field is not implemented in the `2.4.0` version of the integration so that's why you are having this problem. The problem is that this example 3rd-party integration is really just an example and does not implement all the CIF features and this is now missing. I'll discuss with the team to decide how we will fix that.

**Comment by nikhilkumar24dev** [comment]
Thanks @cjelger for the response. 
Actually we are trying to build the 3rd party integration using your reference Schema and Node APIs.

**Comment by cjelger** [comment]
The code here is really just an example, it does not implement and support all CIF features. You see this here:

https://github.com/adobe/commerce-cif-graphql-integration-reference/blob/master/src/local/dispatcher.js#L215

We don't support anything more, no cart, checkout, etc, it's really just a starting point for real integrations.

**Comment by nikhilkumar24dev** [comment]
Got it @cjelger, We have modified the Loaders Js and other JS files to get the products and category data other than Magento.
I understand, we need to modify the reference project to build our own 3rd party integrations.

**Comment by nikhilkumar24dev** [comment]
@cjelger -  Do we have anything coming up for cart, checkout etc in coming releases for this 3rd party implementation ?

**Comment by nikhilkumar24dev** [comment]
@cjelger 
If we create our own createCustomer resolver out of schema it somehow doesn't recognize it. 
![image](https://user-images.githubusercontent.com/71063587/94191669-7c924b80-fecb-11ea-83f5-2ed7d5eeffab.png)


It throws below error although it's available in schema 2.3.5:
{
    "errors": [
        {
            "locations": [
                {
                    "column": 5,
                    "line": 2
                }
            ],
            "message": "Cannot query field \"createCustomer\" on type \"Mutation\". Did you mean \"createEmptyCart\"?"
        }
    ]
}

**Comment by cjelger** [comment]
No, we will not further develop the example integration.

**Comment by nikhilkumar24dev** [comment]
@cjelger - Thanks for the info. 
So the user should go ahead and implement the createCustomer and other functionalities from this schema to further use other CIF features ?
